Change laws and add CartesianClosed
conal/denotational-hardware pull request #13
Opened 2021-06-12 23:31 UTC by bolt12

This PR is still a WIP. I added universal laws for products in `Cartesian` and for exponentials in `CartesianClosed`.

I am stuck in one proof (see the hole), help and suggestions on how to improve are welcome 😄

2021-06-13 02:50 UTC, conal commented on Categorical/Laws.agda
> +           → (k ≈ curry f) ⇔ (f ≈ apply ∘ first k)
Considering the definition of `uncurry`, you could write

``` agda
k ≈ curry f ⇔ f ≈ uncurry k
```

which rhymes nicely. Where did you find your definition for `∀-exp`?

2021-06-13 02:50 UTC, conal commented on Functions/Laws.agda
> +            → {!!}
So far, I'm not seeing how to prove this one without extensionality.

2021-06-13 10:02 UTC, bolt12 commented on Categorical/Laws.agda
> +        → (k ≈ f ▵ g) ⇔ ( (exl ∘ k ≈ f) ×ₚ (exr ∘ k ≈ g) )
> Did you try using _×_ from Categorical.Object? If there was an error, what was the message?

I did! I believe the error was related to Product type class, I think I can add `⦃ _ : Products (Set q) ⦄` and it will work!

> Wonderful! Much more elegant this way. Can you add and as lemmas/definitions in Cartesian rather than fields.

Thank you :D I dont think I understood the second part, what is `and`? Are  you referring to `_×ₚ_`?

2021-06-13 10:02 UTC, bolt12 commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
good question, it is! You just solve the equation where `k = id`

2021-06-13 10:03 UTC, bolt12 commented on Functions/Laws.agda
> +          (λ k≡<f,g>
Yes, I will change to that!

2021-06-13 10:06 UTC, bolt12 commented on Categorical/Laws.agda
> +           → (k ≈ curry f) ⇔ (f ≈ apply ∘ first k)
Wikipedia has something on it: https://en.wikipedia.org/wiki/Exponential_object

But I prefer https://www4.di.uminho.pt/~jno/ps/pdbc.pdf (page 48, def 2.83)

2021-06-13 10:07 UTC, bolt12 commented on Functions/Laws.agda
> +            → {!!}
Thanks for giving it a try!

2021-06-13 15:40 UTC, conal commented on Categorical/Laws.agda
> +        → (k ≈ f ▵ g) ⇔ ( (exl ∘ k ≈ f) ×ₚ (exr ∘ k ≈ g) )
Oops. I just fixed my earlier comment.

2021-06-13 15:50 UTC, conal commented on Categorical/Laws.agda
> +        → (k ≈ f ▵ g) ⇔ ( (exl ∘ k ≈ f) ×ₚ (exr ∘ k ≈ g) )
> I believe the error was related to `Product` type class, I think I can add `⦃ _ : Products (Set q) ⦄` and it will work!

Ah, but then *uses* of `∀▵` will have difficulty fulfilling that constraint. The problem is that `Functions.Type` give instances for `Set 0ℓ`, not `Set o` for arbitrary `o : Level`, which is one of the simplifications I made in this new repository. Alternatively, simplify away `q` for now, requiring it to be zero. I’m inclined to leave `_×ₚ_` here and take up the issue later.

At some point, I think we’ll have a compelling use for generalizing `Functions.*` from `Set` to `Set o`.

2021-06-13 18:35 UTC, conal commented on Functions/Laws.agda
> +            → {!!}
Ultimately I do want the project to be free of all postulates. As an intermediate step, however, I don’t mind if you want to use extensionality in this PR. We can add a new issue to revisit the instance and get some more eyes on the question.

If we add extensionality *as a postulate*, I think we’ll have to comment out the `--safe` pragma in this module and every module that uses it (transitively). Hopefully the commented out pragmas will help remind us to revisit and make it a little easier to reactivate when we’ve removed the postulate.

As an alternative to postulating extensionality, I’d first try parametrizing by a proof of extensionality, I guess of type `ExtensionalityImplicit 0ℓ 0ℓ` from `Axiom.Extensionality.Propositional`. That proof might be a parameter to a submodule containing the instance that needs extensionality.

2021-06-13 20:35 UTC, bolt12 commented on Categorical/Laws.agda
> +        → (k ≈ f ▵ g) ⇔ ( (exl ∘ k ≈ f) ×ₚ (exr ∘ k ≈ g) )
> Ah, but then uses of ∀▵ will have difficulty fulfilling that constraint. The problem is that Functions.Type give instances for Set 0ℓ, not Set o for arbitrary o : Level, which is one of the simplifications I made in this new repository. Alternatively, simplify away q for now, requiring it to be zero. I’m inclined to leave _×ₚ_ here and take up the issue later.

I have added  `⦃ _ : Products (Set q) ⦄`

2021-06-13 22:19 UTC, conal requested changes
Looking good. Almost there.

2021-06-13 22:19 UTC, conal commented on Functions/Laws.agda
> +           , (λ { {a} → cong exr k≡f▵g })
“`k≈f▵g`” is a more accurate name, right?

I don’t think you need to mention “`{a}`”. How about the following:

``` agda
(λ k≈f▵g → cong exl k≈f▵g , cong exr k≈f▵g)
```

or better:

``` agda
(cong exl ▵ cong exr)
```

2021-06-13 22:19 UTC, conal commented on Functions/Laws.agda
> +          )
``` agda
(λ (exl∘k≈f , exr∘k≈g) → cong₂ _,_ exl∘k≈f exr∘k≈g)
```

or even

``` agda
(uncurry (cong₂ _,_))
```

2021-06-13 22:24 UTC, conal commented on Functions/Laws.agda
> +          )
Sometimes point-free forms that would seem to work out do not, because of implicits.

2021-06-13 22:52 UTC, conal commented on Categorical/Laws.agda
> +        → (k ≈ f ▵ g) ⇔ ( (exl ∘ k ≈ f) ×ₚ (exr ∘ k ≈ g) )
> I have added  `⦃ _ : Products (Set q) ⦄`

Hm. I think this constraint will make the instance unusable except when `q` is zero.

2021-06-14 08:14 UTC, bolt12 commented on Categorical/Laws.agda
> +        → (k ≈ f ▵ g) ⇔ ( (exl ∘ k ≈ f) ×ₚ (exr ∘ k ≈ g) )
Yeah, I tried it and it forces `q` to be `zero` :( Going to change back to `_×ₚ_`

2021-06-14 08:19 UTC, bolt12 commented on Functions/Laws.agda
> +           , (λ { {a} → cong exr k≡f▵g })
I will try that!! Thank you! 😄

2021-06-14 08:20 UTC, bolt12 commented on Functions/Laws.agda
> +          )
Ah nice! maybe that wont be enough, I think it needs `(id x id)` but I will try that, thank  you! 😄

2021-06-14 20:04 UTC, bolt12 commented on Functions/Laws.agda
> +           , (λ { {a} → cong exr k≡f▵g })
It seems Agda needs the {a} parameter :/

2021-06-14 20:04 UTC, bolt12 commented on Functions/Laws.agda
> +          )
Yeah in this case it needs the implicits!

2021-06-17 11:44 UTC, bolt12 commented
@conal how's this version?

2021-06-17 15:38 UTC, conal reviewed
Oops. I thought I had left a review comment, but it seems I forgot to hit the "Submit review" button.

2021-06-20 12:09 UTC, bolt12 commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
I am having trouble proving this with `_≈_`, for `_≡_` is easy.

What I have so far:

```agda
record CartesianClosed {obj : Set o} ⦃ _ : Products obj ⦄
                       ⦃ _ : Exponentials obj ⦄ (_⇨′_ : obj → obj → Set ℓ)
                       q ⦃ _ : Equivalent q _⇨′_ ⦄
                       ⦃ _ : Products (Set q) ⦄
                       ⦃ _ : R.CartesianClosed _⇨′_ ⦄
       : Set (suc o ⊔ ℓ ⊔ suc q) where
  private infix 0 _⇨_; _⇨_ = _⇨′_
  field
    ⦃ ⇨Cartesian ⦄ : Cartesian _⇨_ q

    ∀-exp : ∀ {f : a × b ⇨ c} {k : a ⇨ (b ⇛ c)}
           → (k ≈ curry f) ⇔ (f ≈ uncurry k)
           -- → (k ≈ curry f) ⇔ (f ≈ apply ∘ (k ⊗ id))
           -- → (k ≈ curry f) ⇔ (f ≈ apply ∘ first k)

    curry≈ : ∀ {f g : a × b ⇨ d}
           → f ≈ g → curry f ≈ curry g

  curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
  curry-apply =  from ∀-exp ⟨$⟩ {!!}
    where open import Function.Equality
          open Function.Equivalence.Equivalence
```

So close, yet so far 😛

2021-06-20 14:55 UTC, conal commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
How about first proving that `apply ≈ uncurry id`?

2021-06-20 19:45 UTC, bolt12 commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
It seems type class inference gets in the way. When I try to prove that `apply` turns yellow

2021-06-20 19:50 UTC, conal commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
Got it. We can meet up on Discord for a screen share and work through it.

2021-06-20 20:03 UTC, bolt12 commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
This one is challenging me :P

2021-06-21 18:59 UTC, bolt12 commented on Categorical/Laws.agda
> +    curry-apply : ∀ {a b : obj} → id { a = a ⇛ b } ≈ curry apply
Proved!!

2021-06-21 19:01 UTC, bolt12 commented
All good now! 😄  Please let me know what you think about this version, I'll be more than happy to work it out!

2021-06-21 19:04 UTC, merged

2021-06-21 19:04 UTC, conal commented
Hooray! Thanks for hanging in with this one. I'm glad it worked out. :)

2021-06-21 19:05 UTC, bolt12 commented
Me too! 😄  On to the next one!

2021-06-21 19:28 UTC, conal commented
@bolt12 I made a post-PR pass. Please let me know if you have any questions or objections.

Also, maybe you'd be interested in "`TODO: prove exl▵exr rather than assuming`" in `Categorical.Laws`.